type Telegram {
  from: UserName!
  to: UserName!
  message: String!
  category: Category!
  priority: Priority
}

type TelegraphStation {
  eventBus: String!
  source: EventSource!
  detailType: EventDetailType!
  detail: Telegram!
}

enum UserName {
  Bob
  Alice
}

enum Category {
  PERSONAL
  BUSINESS
}

enum Priority {
  NORMAL
  URGENT
}

enum EventSource {
  Telegraph
}

enum EventDetailType {
  NewTelegram
}

# type Query {
#    get(id: ID!): String!
# }

type Mutation {
  # composeTelegram(telegram: Telegram!): String!
  sendTelegram(telegraphStation: TelegraphStation!): String!
}

schema {
  # query: Query
  mutation: Mutation
}
