schema {
  query: Query
  mutation: Mutation
}

type Query {
  _empty: String
}

type Mutation {
  sendTelegram(telegraph: TelegraphInput!): AWSJSON
}

input TelegraphInput {
  source: EventSource!
  detailType: EventDetailType!
  detail: TelegramInput!
}

input TelegramInput {
  from: String!
  to: String!
  message: String!
  category: Category!
  priority: Priority!
  translate: Language!
}

enum EventSource {
  Telegraph
}

enum EventDetailType {
  ComposeTelegram
}

enum Category {
  PERSONAL
  BUSINESS
}

enum Priority {
  NORMAL
  URGENT
}

enum Language {
  FR
}